// delicious-meals-vue/src/App.vue
<template>
  <div id="app">
    <h1>delicious meals</h1>
    <h2>vote for the winner</h2>
    <VotingStage
      :left="currentPair[0]"
      :right="currentPair[1]"
      @selectWinner="selectWinner"
    />
    <div v-if="previousPair.length && previousWinner">
      <h2>previous match</h2>
      <VotingStage
        :active="false"
        :left="previousPair[0]"
        :right="previousPair[1]"
        :winner="previousWinner"
      />
    </div>
    <div class="stats">
      <ol>
        <li v-for="(meal, index) in topMeals" :key="index">
          <MealStat :meal="meal" />
        </li>
      </ol>
      <ol>
        <li v-for="chef in topChefs" :key="chef.author">
          <ChefStat :chef="chef" />
        </li>
      </ol>
    </div>
    <footer>
      <h2>stats</h2>
      <p>
        <strong>{{ totalVotes }}</strong> votes
        <strong>{{ totalMeals }}</strong> meals 
        <strong>{{ totalAuthors }}</strong> chefs 
      </p>
    </footer>
  </div>
</template>

<script>
/* eslint-disable */
import MealStat from './components/MealStat.vue'
import ChefStat from './components/ChefStat.vue'
import VotingStage from './components/VotingStage';

export default {
  name: 'app',
  components: {
    MealStat,
    ChefStat,
    VotingStage,
  },
  created() {
    this.loadStats();
    this.loadPair();
  },
  data() {
    return {
      topMeals: [],
      topChefs: [],
      totalMeals: 0,
      totalAuthors: 0,
      totalVotes: 0,
      currentPair: [],
      previousPair: [],
      previousWinner: undefined,
    };
  },
  methods: {
    async loadStats() {
      try {
        const response = await fetch('http://localhost:3000/stats/');
        const stats = await response.json();
        this.topMeals = stats.topMessages;
        this.topChefs = stats.topAuthors;
        this.totalMeals = stats.totalMeals;
        this.totalAuthors = stats.totalAuthors;
        this.totalVotes = stats.totalVotes;
      } catch(e) {
        console.error(e);
      }
    },
    async loadPair() {
      const response = await fetch('http://localhost:3000/meals/pair');
      const json = await response.json();
      this.currentPair = json;
    },
    async postVote(winnerId, loserId) {
      const response = await fetch('http://localhost:3000/meals/vote', {
        method: 'POST',
        body: JSON.stringify({ winnerId, loserId }),
        headers: { 'Content-Type': 'application/json' },
      });
      const json = await response.json();
      return json;
    },
    async selectWinner(winner) {
      let winnerId, loserId;

      if (winner.id === this.currentPair[0].id) {
        winnerId = this.currentPair[0].id;
        loserId = this.currentPair[1].id;
      } else {
        winnerId = this.currentPair[1].id;
        loserId = this.currentPair[0].id;
      }

      const response = await this.postVote(winnerId, loserId);

      // ugh bad api
      this.previousPair = [];
      if (response.winner.id === this.currentPair[0].id) {
        this.previousPair[0] = response.winner;
        this.previousPair[1] = response.loser;
      } else {
        this.previousPair[0] = response.loser;
        this.previousPair[1] = response.winner;
      }

      this.previousWinner = winner.id;
      this.loadPair();
      this.loadStats();
    },
  }
}
</script>

<style>
body {
  --color-black: #282c34;
  --color-red: #e06c75;
  --color-green: #98c379;
  --color-yellow: #e5c07b;
  --color-blue: #61afef;
  --color-cyan: #56b6c2;
  --color-white: #dcdfe4;

  font-family: 'Fira Code', 'Consolas', monospace;
  margin: 0 auto;
  max-width: 100ex;
  line-height: 1.5;
  font-size: 10pt;
  background-color: var(--color-black);
}
h1, h2 {
  text-align: center;
}
footer {
  text-align: center;
}

#app {
  background-color: var(--color-black);
  color: var(--color-white);
}
#app .c-black { color: var(--color-black); }
#app .c-red { color: var(--color-red); }
#app .c-green { color: var(--color-green); }
#app .c-yellow { color: var(--color-yellow); }
#app .c-blue { color: var(--color-blue); }
#app .c-magenta { color: var(--color-magenta); }
#app .c-cyan { color: var(--color-cyan); }
#app .c-white { color: var(--color-white); }

.stats {
  display: flex;
}
.stats ol {
  flex-grow: 1;
}
.stats ol li {
  margin-bottom: 1rem;
}
</style>

// delicious-meals-svelte/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import ChefStat from './ChefStat.svelte';
  import MealStat from './MealStat.svelte';
  import Competitor from './Competitor.svelte';

  let stats = null;
  let pair = null;
  let prevPair = null;
  let prevWinnerId = null;

  async function fetchStats() {
    const response = await fetch('http://localhost:3000/stats/');
    const newStats = await response.json();
    stats = newStats;
  }

  async function loadPair() {
    const response = await fetch('http://localhost:3000/meals/pair');
    const newPair = await response.json();
    pair = newPair;
  }

  async function vote(winnerId, loserId) {
    const response = await fetch('http://localhost:3000/meals/vote', {
      method: 'POST',
      body: JSON.stringify({ winnerId, loserId }),
      headers: { 'Content-Type': 'application/json' },
    });
    const result = await response.json();

    prevPair = pair;
    prevWinnerId = winnerId;

    // bad, bad api
    if (result.winner.id === pair[0].id) {
      prevPair[0] = result.winner;
      prevPair[1] = result.loser;
    } else {
      prevPair[0] = result.loser;
      prevPair[1] = result.winner;
    }

    loadPair();
    fetchStats();
  }

  onMount(() => {
    fetchStats();
    loadPair();
  });
</script>

<main>
  <h1>svelte meals</h1>

  {#if pair}
    <div class="voting-stage">
      <Competitor competitor={pair[0]} on:vote="{() => vote(pair[0].id, pair[1].id)}"/>
      <Competitor competitor={pair[1]} on:vote="{() => vote(pair[1].id, pair[0].id)}"/>
    </div>
  {/if}

  {#if prevPair}
    <div class="voting-stage">
      <Competitor competitor={prevPair[0]} winner="{prevWinnerId === prevPair[0].id}"/>
      <Competitor competitor={prevPair[1]} winner="{prevWinnerId === prevPair[1].id}"/>
    </div>
  {/if}

  {#if stats}
    <div class="stats">
      <div>
        <h2>top ten meals</h2>
        <ol>
          {#each stats.topMessages as meal}
            <li>
              <MealStat {meal}/>
            </li>
          {/each}
        </ol>
      </div>

      <div>
        <h2>top ten chefs</h2>
        <ol>
          {#each stats.topAuthors as chef}
            <li>
              <ChefStat {chef}/>
            </li>
          {/each}
        </ol>
      </div>
    </div>
  {/if}
</main>

{#if stats}
  <footer>
    <strong>{stats.totalVotes}</strong> votes
    <strong>{stats.totalMeals}</strong> meals
    <strong>{stats.totalAuthors}</strong> chefs
  </footer>
{/if}

<style>
  main {
    max-width: 100ex;
    margin: 0 auto;
  }
  h1, h2 {
    text-align: center;
  }

  .stats {
    display: flex;
  }
  .stats > div {
    flex-grow: 1;
  }
  .stats ol li {
    margin-bottom: .5rem;
  }

  .voting-stage {
    display: flex;
    justify-content: space-around;
    padding: 1rem 0;
  }

  .winner {
    color: green;
  }
  .loser {
    color: red;
  }

  footer {
    text-align: center;
    margin-bottom: 2rem;
  }

</style>
